#!/usr/bin/env ruby -w

require 'rake'

module Slow
  module_function
  def spec?(fn)
    open(fn) { |f| f.gets !~ /fast_helper/ }
  end
end

slow_specs = FileList['spec/**/*_spec.rb'].select { |fn| Slow.spec?(fn) }
if slow_specs.any?
  puts "Running slow specs: #{slow_specs}"
  system "rspec #{slow_specs}"
else
  puts "Unable to find any slow specs"
  exit(-1)
end
